/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package symposium;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;

/**
 *
 * @author Dummy
 */
public class Events extends javax.swing.JFrame {

    /**
     * Creates new form Events
     */
    
    public Connection con;
    public int i;
    public Events() {
        initComponents();
        try{
            ImageIcon I = new ImageIcon (Register.class.getResource("images/pec.jpg"));
            peclogo1.setIcon(I);
            ImageIcon J = new ImageIcon (Register.class.getResource("images/csi.png"));
            csilogo1.setIcon(J);
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:registration","","");
            //JScrollPane scroller = new JScrollPane(details, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED );
        } 
           catch (ClassNotFoundException ex) {
            System.out.println("Class Not Found");
        } catch (SQLException ex) {
            System.out.println("connection not established");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        peclogo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        csilogo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        event1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        filter1 = new javax.swing.JComboBox();
        search1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        count = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextPane();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        peclogo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel1.setText("PANIMALAR ENGINEERING COLLEGE");

        csilogo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel2.setText("31st NATIONAL CSI STUDENT CONVENTION");

        jLabel3.setText("EVENT");

        event1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PPT", "PROJECT", "BEST MANAGER", "POSTER", "AD ZAP", "MOBILE APP", "WEB DESIGN", "CODE DEBUGGING", "TECHNICAL QUIZ" }));
        event1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event1ActionPerformed(evt);
            }
        });

        jLabel7.setText("FILTER");

        filter1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "FINALISTS", "WINNERS" }));
        filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter1ActionPerformed(evt);
            }
        });

        search1.setText("CLOSE");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        count.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        count.setForeground(new java.awt.Color(153, 0, 153));
        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");

        details.setContentType("text/html"); // NOI18N
        details.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(details);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(peclogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(csilogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(search1)
                        .addGap(77, 77, 77)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(event1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153))
                    .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(peclogo1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(csilogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(event1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(filter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search1)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_search1ActionPerformed

    public String event, filter;
    
    private void event1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event1ActionPerformed
        event = (String) event1.getSelectedItem();
        if(event.equals("PPT"))  event = "ppt";
        if(event.equals("PROJECT"))  event = "project";
        if(event.equals("BEST MANAGER"))  event = "bestmanager";
        if(event.equals("POSTER"))  event = "poster";
        if(event.equals("AD ZAP"))  event = "adzap";
        if(event.equals("MOBILE APP"))  event = "app";
        if(event.equals("TECHNICAL QUIZ"))  event = "quiz";
        if(event.equals("WEB DESIGN"))  event = "web";
        if(event.equals("CODE DEBUGGING"))  event = "code";
    }//GEN-LAST:event_event1ActionPerformed

    public Statement s;
    public ResultSet rs;
    public String name, regid, coll;
    public String query =null, data =null, position = null;
    
    private void filter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter1ActionPerformed
        filter = (String) filter1.getSelectedItem();
        if ( filter.equals("ALL")){
            try {
                query = "select student.name,college,student.regno from "+event+" INNER JOIN student on "+event+".regno = student.regno";
                System.out.println(query);
                s= con.createStatement();
                s.executeQuery(query);
                rs = s.getResultSet();
                i=0;
                data ="<html> <table> <b> <tr bgcolor = red> <td>REGNO</td> <td>NAME</td> <td>COLLEGE</td> </tr> </b>";
                while(rs.next()){
                    regid = rs.getString("regno");
                    int regno = Integer.parseInt(regid);
                    regid = "CSINSC" + String.format("%03d",regno);
                    name = rs.getString("name");
                    coll = rs.getString("college");
                    data = data.concat("<tr> <td>"+regid+"</td> <td>"+name+"</td> <td>"+coll+"</td> </tr>"); 
                    i++;
                }
                data = data.concat("</table></html>");
                details.setText(data);
                count.setText(Integer.toString(i));
            } catch (SQLException ex) {
                System.out.println(ex);
            }    
        }
        if ( filter.equals("FINALISTS")){
            try {
                query = "select student.name,college,student.regno from "+event+" INNER JOIN student on "+event+".regno = student.regno where ("+event+".qualify = 1) ";
                s= con.createStatement();
                s.executeQuery(query);
                rs = s.getResultSet();
                i=0;
                data = "<html> <table> <b> <tr bgcolor = red> <td>REGNO</td> <td>NAME</td> <td>COLLEGE</td> </tr> </b>";
                while(rs.next()){
                    regid = rs.getString("regno");
                    int regno = Integer.parseInt(regid);
                    regid = "CSINSC" + String.format("%03d",regno);
                    name = rs.getString("name");
                    coll = rs.getString("college");
                    data = data.concat("<tr> <td>"+regid+"</td> <td>"+name+"</td> <td>"+coll+"</td> </tr>");
                    i++;
                }
                data = data.concat("</table></html>");
                details.setText(data);
                count.setText(Integer.toString(i));
            } catch (SQLException ex) {
                System.out.println(ex);
            }    
        }
        
        if ( filter.equals("WINNERS")){
            try {
                query = "select student.name,college,student.regno,first,second,third from "+event+" inner join student on "+event+".regno = student.regno where ( first = 1 or second = 1 or third = 1) ";
                s= con.createStatement();
                s.executeQuery(query);
                rs = s.getResultSet();
                i=0;
                data = "<html> <table> <b> <tr bgcolor = red> <td>REGNO</td> <td>NAME</td> <td>COLLEGE</td> <td>POSITION</td>  </tr> </b>";
                while(rs.next()){
                    regid = rs.getString("regno");
                    int regno = Integer.parseInt(regid);
                    regid = "CSINSC" + String.format("%03d",regno);
                    name = rs.getString("name");
                    coll = rs.getString("college");
                    if ( rs.getInt("first") == 1 )
                        position = "I";
                    else if ( rs.getInt("second") == 1)
                        position = "II";
                    else if ( rs.getInt("third") == 1 )
                        position = "III";
                    
                    data = data + "<tr><td>"+regid+"</td><td>"+name+"</td><td>"+coll+"</td><td>"+position+"</td></tr>"; 
                    i++;
                    position = null;
                }
                data = data.concat("</table></html>");
                details.setText(data);
                count.setText(Integer.toString(i));
            } catch (SQLException ex) {
                System.out.println(ex);
            }    
        }
    }//GEN-LAST:event_filter1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        this.dispose();
        AdminPanel a = new AdminPanel();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Events().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel count;
    private javax.swing.JLabel csilogo1;
    private javax.swing.JTextPane details;
    private javax.swing.JComboBox event1;
    private javax.swing.JComboBox filter1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel peclogo1;
    private javax.swing.JButton search1;
    // End of variables declaration//GEN-END:variables
}
