/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package symposium;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dummy
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    public Connection con;
    
    
    public Register() {
            initComponents();
            ImageIcon I = new ImageIcon (Register.class.getResource("images/pec.jpg"));
            peclogo.setIcon(I);
            ImageIcon J = new ImageIcon (Register.class.getResource("images/csi.png"));
            csilogo.setIcon(J);
            paytype.add(cash1);
            paytype.add(dd1);
            
           try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:registration","","");
        } 
           catch (ClassNotFoundException ex) {
            System.out.println("Class Not Found");
        } catch (SQLException ex) {
            System.out.println("connection not established");
        }
           name1.requestFocus();
    }
    
    public String name, college,dept,state,city,year,pay;
    public int csino,ddno,ppt,poster,project,web,ad,best,code,quiz,app,cash,dd;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox();
        paytype = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        peclogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        college1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        city1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        state1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        dept1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        year1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        csino1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ppt1 = new javax.swing.JCheckBox();
        project1 = new javax.swing.JCheckBox();
        quiz1 = new javax.swing.JCheckBox();
        code1 = new javax.swing.JCheckBox();
        best1 = new javax.swing.JCheckBox();
        web1 = new javax.swing.JCheckBox();
        poster1 = new javax.swing.JCheckBox();
        mobile1 = new javax.swing.JCheckBox();
        ad1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        cash1 = new javax.swing.JRadioButton();
        dd1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        ddno1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        csilogo = new javax.swing.JLabel();
        namecheck = new javax.swing.JCheckBox();
        collegecheck = new javax.swing.JCheckBox();
        citycheck = new javax.swing.JCheckBox();
        csicheck = new javax.swing.JCheckBox();
        amountcheck1 = new javax.swing.JCheckBox();
        statecheck1 = new javax.swing.JCheckBox();
        deptcheck1 = new javax.swing.JCheckBox();
        yearcheck1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        mobileno1 = new javax.swing.JTextField();
        mobilecheck1 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        amount1 = new javax.swing.JTextField();
        ddcheck1 = new javax.swing.JCheckBox();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        peclogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel1.setText("PANIMALAR ENGINEERING COLLEGE");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel2.setText("31st NATIONAL CSI STUDENT CONVENTION");

        jLabel3.setText("NAME");

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });

        jLabel4.setText("COLLEGE");

        college1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                college1ActionPerformed(evt);
            }
        });

        jLabel7.setText("CITY");

        city1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city1ActionPerformed(evt);
            }
        });

        jLabel8.setText("STATE");

        state1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar", "Chandigarh", "Dadra and Nagar Haveli", "Daman and Diu", "Lakshadweep", "Delhi", "Puducherry" }));
        state1.setSelectedIndex(23);
        state1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state1ActionPerformed(evt);
            }
        });

        jLabel9.setText("DEPARTMENT");

        dept1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "IT", "ECE", "EEE", "MECH", "CIVIL", "EIE" }));
        dept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept1ActionPerformed(evt);
            }
        });

        jLabel10.setText("YEAR");

        year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV" }));
        year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year1ActionPerformed(evt);
            }
        });

        jLabel11.setText("CSI MEMBERSHIP NO");

        csino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csino1ActionPerformed(evt);
            }
        });

        jLabel12.setText("EVENTS");

        ppt1.setText("PAPER PRESENTATION");
        ppt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppt1ActionPerformed(evt);
            }
        });

        project1.setText("PROJECT PRESENTATION");
        project1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                project1ActionPerformed(evt);
            }
        });

        quiz1.setText("TECH QUIZ");
        quiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz1ActionPerformed(evt);
            }
        });

        code1.setText("CODE DEBUGGING");
        code1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code1ActionPerformed(evt);
            }
        });

        best1.setText("BEST MANAGER");
        best1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                best1ActionPerformed(evt);
            }
        });

        web1.setText("WEB DESIGN");
        web1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                web1ActionPerformed(evt);
            }
        });

        poster1.setText("POSTER DESIGN");
        poster1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poster1ActionPerformed(evt);
            }
        });

        mobile1.setText("MOBILE APP");
        mobile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile1ActionPerformed(evt);
            }
        });

        ad1.setText("AD ZAP");
        ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad1ActionPerformed(evt);
            }
        });

        jLabel13.setText("PAYMENT");

        cash1.setText("CASH");
        cash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash1ActionPerformed(evt);
            }
        });

        dd1.setText("DD");
        dd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dd1ActionPerformed(evt);
            }
        });

        jLabel14.setText("DD NO");

        ddno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddno1ActionPerformed(evt);
            }
        });

        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        csilogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("CONTACT NO");

        mobileno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileno1ActionPerformed(evt);
            }
        });

        jLabel15.setText("AMOUNT");

        amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(peclogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(csilogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cash1)
                        .addGap(31, 31, 31)
                        .addComponent(dd1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ppt1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(project1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(best1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poster1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ad1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2)))
                            .addComponent(ddno1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(code1)
                            .addComponent(web1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(csicheck)
                                .addComponent(quiz1)
                                .addComponent(citycheck)
                                .addComponent(collegecheck)
                                .addComponent(namecheck)
                                .addComponent(statecheck1)
                                .addComponent(deptcheck1)
                                .addComponent(yearcheck1)
                                .addComponent(mobilecheck1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(amountcheck1)
                                .addComponent(mobile1)
                                .addComponent(ddcheck1))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mobileno1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(name1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(college1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(city1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(state1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(year1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dept1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(csino1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(csilogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(peclogo, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namecheck)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(college1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(citycheck)))
                    .addComponent(collegecheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(state1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statecheck1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobileno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(mobilecheck1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deptcheck1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(dept1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(yearcheck1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(csino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ppt1)
                                .addComponent(quiz1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(project1)
                            .addComponent(code1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(best1)
                            .addComponent(web1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poster1)
                            .addComponent(mobile1)))
                    .addComponent(csicheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ad1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cash1)
                        .addComponent(dd1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ddcheck1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel14))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ddno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(amountcheck1)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void college1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_college1ActionPerformed
        college = college1.getText();
        collegecheck.setSelected(true);
        city1.requestFocus();
    }//GEN-LAST:event_college1ActionPerformed

    private void ppt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppt1ActionPerformed
        if ( ppt1.isEnabled()) ppt =-1;
        else ppt = 0;
    }//GEN-LAST:event_ppt1ActionPerformed

    private void best1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_best1ActionPerformed
        if ( best1.isEnabled()) best =-1;
        else best=0;
    }//GEN-LAST:event_best1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.dispose();
        AdminPanel a = new AdminPanel();
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        name = name1.getText();
        namecheck.setSelected(true);
        college1.requestFocus();
    }//GEN-LAST:event_name1ActionPerformed

    private void city1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city1ActionPerformed
        city = city1.getText();
        citycheck.setSelected(true);
        state1.requestFocus();
    }//GEN-LAST:event_city1ActionPerformed

    private void state1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state1ActionPerformed
        state = (String) state1.getSelectedItem();
        statecheck1.setSelected(true);
    }//GEN-LAST:event_state1ActionPerformed

    private void dept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept1ActionPerformed
        dept = (String) dept1.getSelectedItem();
        deptcheck1.setSelected(true);
    }//GEN-LAST:event_dept1ActionPerformed

    private void year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year1ActionPerformed
        year = (String) year1.getSelectedItem();
        yearcheck1.setSelected(true);
        csino1.requestFocus();
        
    }//GEN-LAST:event_year1ActionPerformed

    private void csino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csino1ActionPerformed
        String xyz = csino1.getText();
        csino = Integer.parseInt(xyz);
        csicheck.setSelected(true);
        if(csino == 0)
            amount1.setText("450");
        else
            amount1.setText("300");
        amountcheck1.setSelected(true);
        
    }//GEN-LAST:event_csino1ActionPerformed

    private void quiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz1ActionPerformed
        if(quiz1.isSelected()) quiz =-1;
        else quiz =0;
    }//GEN-LAST:event_quiz1ActionPerformed

    private void project1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_project1ActionPerformed
        if ( project1.isSelected()) project =-1;
        else project =0;
    }//GEN-LAST:event_project1ActionPerformed

    private void code1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code1ActionPerformed
        if( code1.isSelected()) code=-1;
        else code = 0;
    }//GEN-LAST:event_code1ActionPerformed

    private void web1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_web1ActionPerformed
        if ( web1.isSelected() ) web = -1;
        else web =0;
    }//GEN-LAST:event_web1ActionPerformed

    private void poster1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poster1ActionPerformed
        if ( poster1.isSelected()) poster = -1;
        else poster =0;
    }//GEN-LAST:event_poster1ActionPerformed

    private void mobile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile1ActionPerformed
        if ( mobile1.isSelected()) app = -1;
        else app =0;
    }//GEN-LAST:event_mobile1ActionPerformed

    private void ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad1ActionPerformed
        if ( ad1.isSelected() ) ad =-1;
        else ad =0;
    }//GEN-LAST:event_ad1ActionPerformed

    private void cash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash1ActionPerformed
        if ( cash1.isSelected())
        {cash = -1;dd =0;
        pay = "cash";
        ddno1.setEnabled(false);
        ddno = 0;
        }
        else{
           cash =0;cash = -1;
           ddno1.setEnabled(true);
           pay ="dd";
        }
    }//GEN-LAST:event_cash1ActionPerformed

    private void ddno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddno1ActionPerformed
        String abc = ddno1.getText();
        ddno = Integer.parseInt(abc);
         ddcheck1.setSelected(true);
    }//GEN-LAST:event_ddno1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Statement s = con.createStatement();
            int regno = 0 ;
            String query = null ,query1 = null ,prequery = null;
            prequery = "select * from regno";
            try{
            s.execute(prequery);
            ResultSet rs = s.getResultSet();
           
            while(rs.next())
                regno = rs.getInt("no") ;
            }
            catch(Exception e){
                System.out.println(e);
            }
            regno++;
            query = "insert into student (regno,name,college,city,state,contact,dept,year,csino,payment,ddno,amount,ppt,project,bestmanager,poster,adzap,quiz,app,web,code) values ( "+ regno + ",'" + name + "','" + college + "','" + city + "','" + state + "','" + mobileno + "','" +  dept + "','" + year + "'," + csino + ",'" + pay + "'," + ddno + "," + amount + "," + ppt + "," + project + "," + best +"," + poster + "," + ad + "," + quiz + "," + app + "," + web + "," + code + ")";
            System.out.println(query);
            s.execute(query);
            if(ppt==-1){
                query1 = "insert into ppt (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(project==-1)
            {query1 = "insert into project (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(best==-1)
            {  query1 = "insert into bestmanager (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(poster==-1)
            { query1 = "insert into poster (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(ad==-1)
            { query1 = "insert into adzap (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(quiz==-1)
            {  query1 = "insert into quiz (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(app==-1)
            {   query1 = "insert into app (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(web==-1)
            {   query1 = "insert into web (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            if(code==-1)
            {  query1 = "insert into code (regno,name) values ( "+regno+",'"+name+"')";s.execute(query1);}
            
            prequery = "update regno set no ="+regno;
            String reg = "CSINSC";
            reg  = reg + String.format("%03d" , regno);
            s.execute(prequery);
            con.commit();
            JOptionPane.showMessageDialog(null,"REGISTRATION SUCCESSFUL \n REG NO : "+reg);
            
        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dd1ActionPerformed
        if ( dd1.isSelected())
        {dd = -1; cash =0;
        ddno1.setEnabled(true);
        pay ="dd";
        ddno1.requestFocus();
        }
        else{
           dd =0; cash =-1;
           ddno1.setEnabled(false);
           pay = "cash";
           ddno =0;
        }
    }//GEN-LAST:event_dd1ActionPerformed
    
    public String mobileno;
    
    private void mobileno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileno1ActionPerformed
        mobileno = mobileno1.getText();
        mobilecheck1.setSelected(true);
        dept1.requestFocus();
    }//GEN-LAST:event_mobileno1ActionPerformed
    
    public int amount;
    
    private void amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount1ActionPerformed
        String amountcol = amount1.getText();
        amount = Integer.parseInt(amountcol);
        amountcheck1.setSelected(true);
    }//GEN-LAST:event_amount1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ad1;
    private javax.swing.JTextField amount1;
    private javax.swing.JCheckBox amountcheck1;
    private javax.swing.JCheckBox best1;
    private javax.swing.JRadioButton cash1;
    private javax.swing.JTextField city1;
    private javax.swing.JCheckBox citycheck;
    private javax.swing.JCheckBox code1;
    private javax.swing.JTextField college1;
    private javax.swing.JCheckBox collegecheck;
    private javax.swing.JCheckBox csicheck;
    private javax.swing.JLabel csilogo;
    private javax.swing.JTextField csino1;
    private javax.swing.JRadioButton dd1;
    private javax.swing.JCheckBox ddcheck1;
    private javax.swing.JTextField ddno1;
    private javax.swing.JComboBox dept1;
    private javax.swing.JCheckBox deptcheck1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox mobile1;
    private javax.swing.JCheckBox mobilecheck1;
    private javax.swing.JTextField mobileno1;
    private javax.swing.JTextField name1;
    private javax.swing.JCheckBox namecheck;
    private javax.swing.ButtonGroup paytype;
    private javax.swing.JLabel peclogo;
    private javax.swing.JCheckBox poster1;
    private javax.swing.JCheckBox ppt1;
    private javax.swing.JCheckBox project1;
    private javax.swing.JCheckBox quiz1;
    private javax.swing.JComboBox state1;
    private javax.swing.JCheckBox statecheck1;
    private javax.swing.JCheckBox web1;
    private javax.swing.JComboBox year1;
    private javax.swing.JCheckBox yearcheck1;
    // End of variables declaration//GEN-END:variables
}
